name: chat_gpt
description: "A new Flutter project. ChatGPT UI Clone for my fortpolio."
publish_to: 'none'
version: 0.1.1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  build_runner: ^2.4.7
  flutter:
    sdk: flutter
  states_rebuilder: ^6.3.0
  flutter_bloc: ^8.1.3
  hive: ^4.0.0-dev.2
  isar: ^4.0.0-dev.14
  isar_flutter_libs: ^4.0.0-dev.14
  json_annotation: ^4.8.1
  path_provider: ^2.1.1
  uuid: ^4.2.1
  copy_with_extension_gen: ^5.0.4
  copy_with_extension: ^5.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  json_serializable: ^6.7.1

flutter:
  uses-material-design: true
